### ISSUE TITLE
Forget WiFi Network

### ISSUE THREAD

**Issue by itaybre** [Itaybre/WiFi-List#1]
Add option to forget a WiFi network from wishing the app.

`extern void WiFiManagerClientRemoveNetwork(WiFiManagerRef manager, WiFiNetworkRef network);`
Look promising

**Comment by itaybre** [comment]
Implemented in 1.1

**Comment by Joan** [comment]
Thanks for this work and for open-sourcing it!
I was looking for this feature in the current app but the version distributed on iCaughtU is still 1.0. Any plan to update it there? 🙏
