### ISSUE TITLE
Last Joined Ascending and Descending

### ISSUE THREAD

**Issue by Jvella94** [Itaybre/WiFi-List#3]
Sorting does not seem to work correctly. First 3 stay static and the order since last joined does not seem correct either.
iOS 13.5 IPhone XS

**Comment by itaybre** [comment]
Thanks for reporting the issue, Last Joined seems to work for me.
It considers the last of Auto Join and Manual Join.

**Comment by Jvella94** [comment]
For me it seems some elements get stuck/unsorted and the rest do. This doesn't happen on the other filter types and they work correctly. Is there a way I can export the list so you can test it? 🙂

**Comment by itaybre** [comment]
If you enter these network details, do you see a last joined date? either manually or automatic?

**Comment by Jvella94** [comment]
Just checked. The networks that stay in their original position don't have either a manual or automatic join date. The ones that do sort themselves in those positions.

Eg: if I have networks 1,2,3,4,5
And only 123 and 5 have join times (either manual or automatic) 4 stays where it is and 1235 sort themselves between the remaining slots. 

I think best behaviour is to have unknown join times be sorted last for latest and first for oldest?
